CREATE TABLE REGION
(
  ID NUMBER(7),
  NAME VARCHAR2(25) DEFAULT 'New Region' NOT NULL
)
/

ALTER TABLE REGION
  ADD PRIMARY KEY (ID)
/

CREATE TABLE DEPARTMENT
(
  ID NUMBER(7) PRIMARY KEY,
  NAME VARCHAR2(25) NOT NULL,
  REGION_ID NUMBER(7) CONSTRAINT DEPARTMENT_REGION_ID_UK_I UNIQUE
    CONSTRAINT DEPARTMENT_REGION_ID_FK REFERENCES REGION
)
/

CREATE TABLE EMPLOYEE
(
  ID NUMBER(7) PRIMARY KEY,
  LAST_NAME VARCHAR2(25) NOT NULL,
  FIRST_NAME VARCHAR2(25),
  USER_ID CHAR(12) NOT NULL UNIQUE,
  DEPT_ID NUMBER(7)
    CONSTRAINT EMPLOYEE_DEPARTMENT_ID_FK REFERENCES DEPARTMENT,
  START_DATE DATE DEFAULT SYSDATE,
  COMISSION NUMBER(7),
  CONSTRAINT EMPLOYEE_COMISSION_VALUE CHECK (COMISSION > 9 AND COMISSION < 51)
)
/

CREATE INDEX employee_dept_id_i ON EMPLOYEE (DEPT_ID)
/
CREATE INDEX employee_last_name_i ON EMPLOYEE (LAST_NAME)
/
CREATE INDEX department_name_i ON DEPARTMENT (NAME)
/
CREATE INDEX region_name_i ON REGION (NAME)
/

SELECT
  TABLE_NAME,
  COLUMN_NAME,
  DATA_TYPE,
  DATA_PRECISION,
  NULLABLE,
  DATA_DEFAULT,
  CHAR_LENGTH
FROM COLS
ORDER BY TABLE_NAME, COLUMN_ID
/

SELECT * FROM ALL_INDEXES WHERE OWNER='ZIK4122'
/

SELECT * FROM ALL_CONSTRAINTS WHERE TABLE_NAME='EMPLOYEE'
/
