CREATE TABLE WORKER AS SELECT * FROM EMPLOYEE
/
-- query above ^^ copies _only_ data. It does not create indexes, constraints, etc.

ALTER TABLE WORKER ADD PRIMARY KEY (ID) ENABLE
/

ALTER TABLE WORKER
  ADD CONSTRAINT WORKER_DEPARTMENT_ID_FK
    FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT
/

ALTER TABLE DEPARTMENT
  ADD DEPT_ID NUMERIC(7) REFERENCES DEPARTMENT
/

ALTER TABLE WORKER
  ADD TITLE VARCHAR2(30)
/

DROP TABLE EMPLOYEE
/

DROP TABLE DEPARTMENT
/
-- query above ^^ fails because table WORKER refers to DEPARTMENT.
