BEGIN
  INSERT INTO DEPARTMENT VALUES (54, 'Electronics faculty', 44);
  SAVEPOINT add_dept;
  DELETE FROM EMPLOYEE;
  SELECT * FROM EMPLOYEE;
  ROLLBACK TO add_dept;
  SELECT * FROM EMPLOYEE;
  SELECT * FROM DEPARTMENT;
  COMMIT;
END;
/