SELECT *
FROM ALL_CONSTRAINTS
WHERE TABLE_NAME IN ('DEPARTMENT', 'EMPLOYEE', 'REGION')
/

SELECT
  CONS.CONSTRAINT_NAME
FROM ALL_CONSTRAINTS CONS
JOIN ALL_CONS_COLUMNS C ON (CONS.CONSTRAINT_NAME = C.CONSTRAINT_NAME)
WHERE
  CONS.CONSTRAINT_TYPE='U' AND
    CONS.TABLE_NAME='DEPARTMENT' AND
    C.COLUMN_NAME='REGION_ID'
/

-- get constraint name ^^
ALTER TABLE DEPARTMENT DROP CONSTRAINT "SYS_C0023116"
/

ALTER TABLE DEPARTMENT ADD CONSTRAINT NAME_REGION_ID_UNIQUE UNIQUE (NAME, REGION_ID)
/
