SELECT *
FROM ALL_CONSTRAINTS
WHERE TABLE_NAME IN ('DEPARTMENT', 'EMPLOYEE', 'REGION')
/

ALTER TABLE DEPARTMENT DROP CONSTRAINT "DEPARTMENT_REGION_ID_UK_I"
/

ALTER TABLE DEPARTMENT ADD CONSTRAINT NAME_REGION_ID_UNIQUE UNIQUE (NAME, REGION_ID)
/
